services:
  - type: web
    name: trading-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python apps/run_interface.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
