services:
  - type: web
    name: trading-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn apps.run_interface:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DASH_DEBUG
        value: 'false'
